#
# .zshrc - zsh configuration
# plugins:
#   - zsh-autocomplete: https://github.com/marlonrichert/zsh-autocomplete
# 

# if not running interactively, exit.
[[ $- == *i* ]] || return

# environment
EDITOR="nvim"

# history
HISTFILE=$HOME/.zsh/histfile
HISTSIZE=100
SAVEHIST=1000

# prompt
PROMPT="%B%F{cyan}%n@%m %F{white}%~ %F{cyan}%# %f%b"

# alias
alias ls="ls --color=auto"
alias la="ls -lAh"
alias todo="$EDITOR ~/TODO"
alias vim="nvim"

# plugins
PLUGINS_DIR=$HOME/.zsh/plugins
source $PLUGINS_DIR/zsh-autocomplete/zsh-autocomplete.plugin.zsh
source $PLUGINS_DIR/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh

# keybinds
bindkey  "^[[H"    beginning-of-line
bindkey  "^[[F"    end-of-line
bindkey  "^[[3~"   delete-char 
bindkey  "^[[1;5C" forward-word
bindkey  "^[[1;5D" backward-word

# startup
pfetch
